name: Deploy to server 

# directivas 
# evento o trigger
on: push 

# job 
jobs: 
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo 
        run: echo "HolaMundo"
        
  second_job:
    if: false 
    # needs hace referencia en dependencia de jobs 
    needs: first_jobs
    runs-on: ubutu-latest

    steps: 
      - name: Hola mundo 
        run: echo "Hola Mundo"